### PR TITLE
Add new config option activityBackgroundColor

### PR DESCRIPTION
**Pull request by mnahkies**
Allow customisation of the activity background color that shows through when the image is scaled to be smaller than the full screen size.

### CODE REVIEW

**Comment by ArthurHub** [comment]
Hey, thx for the contribution.
Why not use theme to change the activity background?

**Comment by mnahkies** [comment]
Probably due to ignorance. I'll have a better look at the use of themes, and this is likely unnecessary, thanks

**Comment by ArthurHub** [comment]
Sorry, appreciate the time you invested in the code.
keep the good work.

**Comment by mnahkies** [comment]
It's no problem, always happy to learn new things!

**Pull request closed without merging**
