### PR TITLE
image picker bugfix for xiaomi and huawei phones

### PR DESCRIPTION
**Pull request by nicolabeghin**
Fixes empty image picker on huawei and xiaomi phone as in #132. Tested on Xiaomi MI5.

### CODE REVIEW

**Comment by nicolabeghin** [comment]
thanks @ArthurHub . any ETA for  new release including my commit? Right now I'm deploying from your sources but would like to get back to gradle dependencies

**Comment by ArthurHub** [comment]
I want to check the effect of this change on normal devices and add another fix, so I think 2-4 hours.

**Comment by nicolabeghin** [comment]
thanks @ArthurHub

**Comment by ArthurHub** [comment]
published

**Pull request merged**
