### PR TITLE
Fix class not found when unmarshalling for Samsung devices

### PR DESCRIPTION
**Pull request by Vantablack**
Fix for #329 
Tested on `Samsung I9300 Galaxy S III 4.3`

### CODE REVIEW

**Comment by Vantablack** [comment]
Hey @ArthurHub! I've tested and it works by wrapping the Parcel in a Bundle [see also](https://stackoverflow.com/a/34547902/3903483)

**Comment by ArthurHub** [comment]
Awesome! Thank you!
image

**Comment by Vantablack** [comment]
Thanks for the fast reply too! 😊

**Comment by vasskob** [comment]
Hey @ArthurHub! When did you plan publish this Fix?

**Comment by ArthurHub** [comment]
This weekend

**Comment by vasskob** [comment]
Thanks for you help. Issue #329 can be closed. Still have problem with Samsung on my app with JNI.

**Comment by Vantablack** [comment]
Hey @vasskob I found this [issue from another library](https://github.com/bumptech/glide/issues/1523) which happens on, as quoted `Nexus 5x, Android 7.0, Android build NBD90W (October 2016 security patches)`. Also linked was [https://issuetracker.google.com/issues/37123764](https://issuetracker.google.com/issues/37123764).

I'm suspecting it's some Android patches that are causing this issue (?) and not the library itself (it was also marked as a non-library bug in the other project).

**Comment by vasskob** [comment]
Thanks a lot, but i have tested my app also on Nexus 5X but all works fine.

**Pull request merged**
