### PR TITLE
Multitouch option enables image scaling instead of crop overlay manipulation

### PR DESCRIPTION
**Pull request by wrbl606**
I explained my motivation [here](https://github.com/ArthurHub/Android-Image-Cropper/issues/582)

### CODE REVIEW

**Comment by jhavatar** [comment]
Note, multitouch scaling does not work if view was initialized with multitouch enabled.

(multitouch scaling will probably also stop working after onSaveInstanceState -> onRestoreInstanceState)

**Comment by wrbl606** [comment]
Sure, it may be buggy. It was more like an idea for a new feature. I think it'll not be merged anyway so I'll close this PR.

**Comment by jhavatar** [comment]
Agree that good idea and that it should be merged after tweaks. Used this pr in my fork -- that's how i found the bug.

**Comment by wrbl606** [comment]
Oh, ok then. Have you found a way to fix it?

**Comment by jhavatar** [comment]
My tweaks for initialized view are in branch https://github.com/jhavatar/Android-Image-Cropper/tree/multitouch_image_scaling .

Note, I have not investigated/solved onSaveInstanceState -> onRestoreInstanceState.

**Pull request closed without merging**
