### PR TITLE
Toolbar implemented

### PR DESCRIPTION
**Pull request by yayaa**

### CODE REVIEW

**Comment by ArthurHub** [comment]
Hey,
What is the added value of using this toolbar instead of a theme with built-in toolbar?
thx.

**Comment by yayaa** [comment]
Because your crop_image_activity.xml doesn't have Toolbar in it, CropImageActivity crashes when you try to set its theme. AFAIK to use Toolbar you need to remove actionBar and set a theme .NoActionBar then you implement your toolbar, am i right?

**Comment by ArthurHub** [comment]
You can use custom toolbar they way you did it, usually done if you want more control over it, but you can also use standard toolbar by setting the proper theme:
```xml
<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
    android:theme="@style/Base.Theme.AppCompat" />
```
This should work without issues.
What was the crash you were getting?

**Comment by yayaa** [comment]
Yes, but because i used mostly custom toolbar implementation, my own theme is an extension of .NoActionBar so it doesn't have any supportActionBar in it. That was crashing and i thought it would be nice to support both :) So that i can continue to use my own theme with CropImageActivity as well.

**Comment by ArthurHub** [comment]
You can create a theme only for the crop activity with a toolbar, sharing some resources with you main theme but having a built-in toolbar.

I just don't want to add code that is not required by 95% of use-cases.

**Comment by yayaa** [comment]
That's your library :) Thanks for it though.

**Pull request closed without merging**
