### PR TITLE
Fixed permission request, Added optional backdrop.

### PR DESCRIPTION
**Pull request by bpappin**
The permission request was happening too late and causing a crash.
I added code to ask for the permission on startup instead, but left the original code in place.

### CODE REVIEW

**Comment by ArthurHub** [comment]
Why is the permission request too late? at that point does it fails?

**Comment by bpappin** [comment]
It happens when you select a new image to crop (I was testing transparency).
This is the stack trace from the emulator:

```
04-16 11:47:40.879: E/AIC(2759): Failed to load image by URI
04-16 11:47:40.879: E/AIC(2759): java.lang.RuntimeException: Failed to load sampled bitmap: content://media/external/images/media/39
04-16 11:47:40.879: E/AIC(2759): 	at com.theartofdev.edmodo.cropper.BitmapUtils.decodeSampledBitmap(BitmapUtils.java:154)
04-16 11:47:40.879: E/AIC(2759): 	at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:93)
04-16 11:47:40.879: E/AIC(2759): 	at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:26)
04-16 11:47:40.879: E/AIC(2759): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
04-16 11:47:40.879: E/AIC(2759): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-16 11:47:40.879: E/AIC(2759): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
04-16 11:47:40.879: E/AIC(2759): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-16 11:47:40.879: E/AIC(2759): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-16 11:47:40.879: E/AIC(2759): 	at java.lang.Thread.run(Thread.java:818)
04-16 11:47:40.879: E/AIC(2759): Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/39 from pid=2759, uid=10057 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
04-16 11:47:40.879: E/AIC(2759): 	at android.os.Parcel.readException(Parcel.java:1599)
04-16 11:47:40.879: E/AIC(2759): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-16 11:47:40.879: E/AIC(2759): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
04-16 11:47:40.879: E/AIC(2759): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-16 11:47:40.879: E/AIC(2759): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
04-16 11:47:40.879: E/AIC(2759): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
04-16 11:47:40.879: E/AIC(2759): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
04-16 11:47:40.879: E/AIC(2759): 	at com.theartofdev.edmodo.cropper.BitmapUtils.decodeSampledBitmap(BitmapUtils.java:135)
04-16 11:47:40.879: E/AIC(2759): 	... 8 more

```

**Comment by ArthurHub** [comment]
It looks like there is a bug in `isReadExternalStoragePermissionsRequired` because this code wouldn't reach that point unless this method cleared it.
Can you debug it and see why it thinks the permissions are not required when it clearly does, my money is on `isUriRequiresPermissions` method, something with the exception.
Greatly appreciate.

**Comment by bpappin** [comment]
I'm not sure I have time for it this week.

But why bother?
I can just take out the old code that wasn't working and the demo app will still do what it needs to do.

**Comment by ArthurHub** [comment]
I believe i fixed it, it looks like it throws `SecurityException` for you while in my tests it's always `FileNotFoundException`... Android...

I think its important for an application to request permissions only if and when they are required, not all URI's require external storage access so I want to check if it does before it request it.

It's not important for the sample but the relevant code is part of `CropImageHelper` that I created to be used by clients.

**Comment by bpappin** [comment]
Make sure you re building with 23 and the project is set with that minimum. 
you *should* get a security exception. But, you might not if the user has denied several times  (not sure). 

The code I added is a little more robust and will tell the user how to handle the situation.
It should be fairly simple to refactor the code in onPostResume to its own method and call it later (essentially as soon as the user clicks the menu option).

**Comment by ArthurHub** [comment]
It's probably have to do either with the device, I use Moto X, or the source app, Dropbox in my case.

How is your code more robust?

**Comment by bpappin** [comment]
It's doing the recommended practice of providing a rational if the user denies. 
I think i also included a button to the settings page (I usually do).

**Comment by ArthurHub** [comment]
I don't agree, the alert window in not required because the permission request is shown right after the user selected a source that requires it, so it is obvious why it was requested. It's the recommended behavior as documented in `ActivityCompat.shouldShowRequestPermissionRationale`.

If the use denies the permissions a toast notifies if the cancellation due to permissions denial. the user can then either try again or select a source that doesn't require external storage.

**Comment by bpappin** [comment]
Its your codebase. but your case won't hand the user going back and trying again later, as far as I can see.

**Comment by ArthurHub** [comment]
I have cherry-picked the checkerboard but decided to leave the permissions out.
Thx.

**Pull request closed without merging**
